const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Flash,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Arr,
		C3.Behaviors.Tween,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Arr.Exps.Front,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Acts.Destroy
	];
};
self.C3_JsPropNameTable = [
	{Flash: 0},
	{btnBasla: 0},
	{btnBilgi: 0},
	{btnButonlar: 0},
	{kapla: 0},
	{btnFullScreen: 0},
	{btnHome: 0},
	{durum: 0},
	{btnMuzik: 0},
	{btnSes: 0},
	{Sine: 0},
	{btnTekrarOyna: 0},
	{btnileri: 0},
	{btnTekrarOyna2: 0},
	{zarf: 0},
	{zarf2: 0},
	{zarf3: 0},
	{zarf4: 0},
	{zarf5: 0},
	{zarf6: 0},
	{zrf: 0},
	{zrf2: 0},
	{zrf3: 0},
	{zrf4: 0},
	{zrf5: 0},
	{zrf6: 0},
	{Touch: 0},
	{Mouse: 0},
	{Audio: 0},
	{Browser: 0},
	{background: 0},
	{bilgi: 0},
	{game: 0},
	{end: 0},
	{soru: 0},
	{butonSayfa: 0},
	{game2: 0},
	{sira: 0},
	{sorular: 0},
	{dadi: 0},
	{dNo: 0},
	{cevaplar: 0},
	{end2: 0},
	{Tween: 0},
	{muze: 0},
	{kutu: 0},
	{no: 0},
	{gorevD: 0},
	{yonerge: 0},
	{dogruu: 0},
	{yonerge1: 0},
	{zemin: 0},
	{gorevY: 0},
	{sandik: 0},
	{koyuZemin: 0},
	{sandik2: 0},
	{yuzey: 0},
	{Sprite2: 0},
	{sorularr: 0},
	{cevapp: 0},
	{DoYa: 0},
	{Sprite: 0},
	{bos: 0},
	{noo: 0},
	{DY: 0},
	{sandikk: 0},
	{bosCevapp: 0},
	{butonlarr: 0},
	{butonlar2: 0},
	{zarflar: 0},
	{zrfflar: 0},
	{dogru: 0},
	{dogruSayisi: 0},
	{tiklama: 0},
	{rastsay: 0},
	{yanlis: 0},
	{sorusirasi: 0},
	{sorutiklama: 0}
];

self.InstanceType = {
	btnBasla: class extends self.ISpriteInstance {},
	btnBilgi: class extends self.ISpriteInstance {},
	btnButonlar: class extends self.ISpriteInstance {},
	btnFullScreen: class extends self.ISpriteInstance {},
	btnHome: class extends self.ISpriteInstance {},
	btnMuzik: class extends self.ISpriteInstance {},
	btnSes: class extends self.ISpriteInstance {},
	btnTekrarOyna: class extends self.ISpriteInstance {},
	btnileri: class extends self.ISpriteInstance {},
	btnTekrarOyna2: class extends self.ISpriteInstance {},
	zarf: class extends self.ISpriteInstance {},
	zarf2: class extends self.ISpriteInstance {},
	zarf3: class extends self.ISpriteInstance {},
	zarf4: class extends self.ISpriteInstance {},
	zarf5: class extends self.ISpriteInstance {},
	zarf6: class extends self.ISpriteInstance {},
	zrf: class extends self.ISpriteInstance {},
	zrf2: class extends self.ISpriteInstance {},
	zrf3: class extends self.ISpriteInstance {},
	zrf4: class extends self.ISpriteInstance {},
	zrf5: class extends self.ISpriteInstance {},
	zrf6: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	background: class extends self.ISpriteInstance {},
	bilgi: class extends self.ISpriteInstance {},
	game: class extends self.ISpriteInstance {},
	end: class extends self.ISpriteInstance {},
	soru: class extends self.IArrayInstance {},
	butonSayfa: class extends self.ISpriteInstance {},
	game2: class extends self.ISpriteInstance {},
	sorular: class extends self.ISpriteInstance {},
	cevaplar: class extends self.ISpriteInstance {},
	end2: class extends self.ISpriteInstance {},
	muze: class extends self.ISpriteInstance {},
	kutu: class extends self.ISpriteInstance {},
	gorevD: class extends self.ISpriteInstance {},
	yonerge: class extends self.ISpriteInstance {},
	dogruu: class extends self.ISpriteInstance {},
	yonerge1: class extends self.ISpriteInstance {},
	zemin: class extends self.ISpriteInstance {},
	gorevY: class extends self.ISpriteInstance {},
	sandik: class extends self.ISpriteInstance {},
	koyuZemin: class extends self.ISpriteInstance {},
	sandik2: class extends self.ISpriteInstance {},
	yuzey: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	sorularr: class extends self.ISpriteInstance {},
	cevapp: class extends self.ISpriteInstance {},
	DoYa: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	bos: class extends self.ISpriteInstance {},
	DY: class extends self.ISpriteInstance {},
	sandikk: class extends self.ISpriteInstance {},
	bosCevapp: class extends self.ISpriteInstance {},
	butonlarr: class extends self.ISpriteInstance {},
	butonlar2: class extends self.ISpriteInstance {},
	zarflar: class extends self.ISpriteInstance {},
	zrfflar: class extends self.ISpriteInstance {}
}